#!/bin/bash

PACKAGE=ros-noetic-roscpp-serialization

apt-get update && apt-get source $PACKAGE

cd $PACKAGE-*
QUILT_PATCHES=debian/patches quilt import /host/0001-assume-std-allocator-traits.patch
cat /host/roscpp_changelog_entry debian/changelog > tmp_changelog && mv tmp_changelog debian/changelog
debuild && \
cp ../$PACKAGE*.deb /host \
&& echo built ../$PACKAGE*.deb
#debuild -S -sa && \
#debsign -k 0C57A413D27CE91083A40BB3F16FD948B3FEBD64 ../$PACKAGE*.changes && \
#dput ppa:noillians/ros ../$PACKAGE*.changes

exec /bin/bash
